/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoPackage;

import java.sql.*;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DELL
 */
public class AdminPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_playSong = new javax.swing.JButton();
        btn_view_users = new javax.swing.JButton();
        btn_verify_users = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        btn_viewsonglist = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_playSong.setBackground(new java.awt.Color(204, 204, 255));
        btn_playSong.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_playSong.setForeground(new java.awt.Color(153, 153, 255));
        btn_playSong.setText("btn_playSong");
        btn_playSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playSongActionPerformed(evt);
            }
        });
        getContentPane().add(btn_playSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 152, 180, 49));

        btn_view_users.setBackground(new java.awt.Color(204, 204, 255));
        btn_view_users.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_view_users.setForeground(new java.awt.Color(153, 153, 255));
        btn_view_users.setText("View Users");
        btn_view_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_view_usersActionPerformed(evt);
            }
        });
        getContentPane().add(btn_view_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 286, 180, 49));

        btn_verify_users.setBackground(new java.awt.Color(204, 204, 255));
        btn_verify_users.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_verify_users.setForeground(new java.awt.Color(153, 153, 255));
        btn_verify_users.setText("Verify Users");
        btn_verify_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verify_usersActionPerformed(evt);
            }
        });
        getContentPane().add(btn_verify_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 286, 180, 49));

        btn_exit.setBackground(new java.awt.Color(204, 204, 255));
        btn_exit.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(153, 153, 255));
        btn_exit.setText("LOG OUT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 380, 180, 49));

        btn_viewsonglist.setBackground(new java.awt.Color(204, 204, 255));
        btn_viewsonglist.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        btn_viewsonglist.setForeground(new java.awt.Color(153, 153, 255));
        btn_viewsonglist.setText("ViewSong List");
        btn_viewsonglist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewsonglistActionPerformed(evt);
            }
        });
        getContentPane().add(btn_viewsonglist, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 152, 180, 49));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN PANEL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 700, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/music_back.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verify_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verify_usersActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Verify_Users vu=new Verify_Users();
        vu.setVisible(true);
        
    }//GEN-LAST:event_btn_verify_usersActionPerformed

    private void btn_playSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playSongActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MP3Player_GUI mp3=new MP3Player_GUI();
        mp3.setVisible(true);
    }//GEN-LAST:event_btn_playSongActionPerformed

    private void btn_viewsonglistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewsonglistActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewSongList vsl=new ViewSongList();
        vsl.setVisible(true);
    }//GEN-LAST:event_btn_viewsonglistActionPerformed

    private void btn_view_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_view_usersActionPerformed
        this.dispose();
        View_Users user1=new View_Users();
        user1.setVisible(true);
        
    }//GEN-LAST:event_btn_view_usersActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminLogin().setVisible(true);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_playSong;
    private javax.swing.JButton btn_verify_users;
    private javax.swing.JButton btn_view_users;
    private javax.swing.JButton btn_viewsonglist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
