/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    
    private String adminnm=new String("admin");
    private String admin_password=new String("admin@2001");
    String admin;
    String passadmin;
    
    public AdminLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_admin_nm = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_admin_login = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(696, 444));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(164, 147, 171, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(164, 231, 171, 50);

        txt_admin_nm.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txt_admin_nm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_admin_nmActionPerformed(evt);
            }
        });
        getContentPane().add(txt_admin_nm);
        txt_admin_nm.setBounds(360, 150, 190, 50);

        txt_password.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(txt_password);
        txt_password.setBounds(360, 230, 190, 50);

        btn_admin_login.setBackground(new java.awt.Color(153, 153, 153));
        btn_admin_login.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_admin_login.setText("LOGIN");
        btn_admin_login.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btn_admin_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_admin_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_admin_login);
        btn_admin_login.setBounds(390, 320, 160, 40);

        btn_reset.setBackground(new java.awt.Color(153, 153, 153));
        btn_reset.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_reset.setText("RESET");
        btn_reset.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset);
        btn_reset.setBounds(190, 320, 160, 40);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 400, 90, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/admin.jpeg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 700, 440);

        setSize(new java.awt.Dimension(712, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_admin_nmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_admin_nmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_admin_nmActionPerformed

    private void btn_admin_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_admin_loginActionPerformed
        // TODO add your handling code here:
        admin=txt_admin_nm.getText();
        passadmin= txt_password.getText().toString();
        if(admin.equals(adminnm)&&passadmin.equals(admin_password))
        {
            JOptionPane.showMessageDialog(null,"Admin Login Successful!!!");
            this.hide();
            AdminPanel a1=new AdminPanel();
            a1.setVisible(true);
            
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Login Failed");
            
        }
        
    }//GEN-LAST:event_btn_admin_loginActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        txt_admin_nm.setText("");
        txt_password.setText("");
        
    }//GEN-LAST:event_btn_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_admin_login;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txt_admin_nm;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
