/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoPackage;

/**
 *
 * @author DELL
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        admin_btn = new javax.swing.JButton();
        user_login_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 855));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(204, 162, 146));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AUTHENTICATION BASED MUSIC PLAYER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 71));

        btn_exit.setBackground(new java.awt.Color(255, 153, 153));
        btn_exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.setBorder(new javax.swing.border.MatteBorder(null));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 182, 43));

        admin_btn.setBackground(new java.awt.Color(255, 153, 153));
        admin_btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        admin_btn.setText("ADMIN LOGIN");
        admin_btn.setBorder(new javax.swing.border.MatteBorder(null));
        admin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_btnActionPerformed(evt);
            }
        });
        getContentPane().add(admin_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 182, 43));

        user_login_btn.setBackground(new java.awt.Color(255, 153, 153));
        user_login_btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        user_login_btn.setText("USER LOGIN");
        user_login_btn.setBorder(new javax.swing.border.MatteBorder(null));
        user_login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_login_btnActionPerformed(evt);
            }
        });
        getContentPane().add(user_login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 182, 43));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/mainback.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 580));

        setSize(new java.awt.Dimension(897, 622));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_btn_exitActionPerformed

    private void admin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_btnActionPerformed
        // TODO add your handling code here:
        this.hide();
        AdminLogin adminl=new AdminLogin();
        adminl.setVisible(true);
    }//GEN-LAST:event_admin_btnActionPerformed

    private void user_login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_login_btnActionPerformed
        // TODO add your handling code here:
        this.hide();
        LoginUser u1=new LoginUser();
        u1.setVisible(true);
    }//GEN-LAST:event_user_login_btnActionPerformed

    public static void main(String[] args) {
        new MainFrame().setVisible(true);
    }
         
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_btn;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton user_login_btn;
    // End of variables declaration//GEN-END:variables
}
