/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoPackage;

import java.io.File;
import java.io.FileFilter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author DELL
 */
public class MP3Player_GUI extends javax.swing.JFrame {

    
    MP3_Player_Code MC=new MP3_Player_Code();
    ArrayList<File> songfiles=new ArrayList<>();
    int selectedSongIndex=0;
    
    public static int count;        
    
    public MP3Player_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_loop = new JLabel();
        lbl_loop.setSize(70,70);

        ;
        lbl_stop = new javax.swing.JLabel();
        lbl_pause = new javax.swing.JLabel();
        lbl_open = new javax.swing.JLabel();
        lbl_songnm = new javax.swing.JLabel();
        btn_play = new javax.swing.JButton();
        counter = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setLocationByPlatform(true);
        getContentPane().setLayout(null);

        lbl_loop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/repeat.png"))); // NOI18N
        lbl_loop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_loopMouseReleased(evt);
            }
        });
        getContentPane().add(lbl_loop);
        lbl_loop.setBounds(10, 110, 70, 80);

        lbl_stop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/stop.png"))); // NOI18N
        lbl_stop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_stopMouseReleased(evt);
            }
        });
        getContentPane().add(lbl_stop);
        lbl_stop.setBounds(100, 110, 70, 70);

        lbl_pause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/pause.png"))); // NOI18N
        lbl_pause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_pauseMouseReleased(evt);
            }
        });
        getContentPane().add(lbl_pause);
        lbl_pause.setBounds(330, 110, 70, 70);

        lbl_open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/open.png"))); // NOI18N
        lbl_open.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_openMouseReleased(evt);
            }
        });
        getContentPane().add(lbl_open);
        lbl_open.setBounds(420, 110, 70, 70);
        lbl_open.getAccessibleContext().setAccessibleName("lbl_open");

        lbl_songnm.setBackground(new java.awt.Color(16, 16, 108));
        lbl_songnm.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        lbl_songnm.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_songnm);
        lbl_songnm.setBounds(10, 10, 490, 40);
        lbl_songnm.getAccessibleContext().setAccessibleName("lbl_songnm");

        btn_play.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/play.png"))); // NOI18N
        btn_play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_playActionPerformed(evt);
            }
        });
        getContentPane().add(btn_play);
        btn_play.setBounds(190, 50, 130, 130);

        counter.setForeground(new java.awt.Color(0, 0, 102));
        getContentPane().add(counter);
        counter.setBounds(340, 60, 120, 30);

        jButton1.setText("NEXt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 50, 55, 23);

        jButton2.setText("Previous");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 50, 73, 23);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/arrow.png"))); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 0, 50, 30);

        setBounds(0, 0, 525, 228);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_playActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_playActionPerformed
        // TODO add your handling code here:
        MC.Resume();
    }//GEN-LAST:event_btn_playActionPerformed

    private void lbl_stopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_stopMouseReleased
        // TODO add your handling code here:
        MC.Stop();
    }//GEN-LAST:event_lbl_stopMouseReleased

    private void lbl_pauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_pauseMouseReleased
        // TODO add your handling code here:
        MC.Pause();
    }//GEN-LAST:event_lbl_pauseMouseReleased

    private void lbl_openMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_openMouseReleased
        // TODO add your handling code here:
        JFileChooser chooser=new JFileChooser();
        chooser.setMultiSelectionEnabled(true);
        int returnval=chooser.showOpenDialog(this);
        if(returnval==JFileChooser.APPROVE_OPTION)
        {
            File[] files=chooser.getSelectedFiles();
            for(File file:files)
            {
                songfiles.add(file);
            }
            startProgram(selectedSongIndex);
        }
        else
            System.out.println("No Files Selected!");
        
        
    }//GEN-LAST:event_lbl_openMouseReleased

    private void lbl_loopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_loopMouseReleased
        // TODO add your handling code here:
        switch(count)
        {
            case 0:
                count=1;
                counter.setText("LOOP ON");
                break;
            case 1:
                count=0;
                counter.setText("LOOP OFF");
                break;
        }
    }//GEN-LAST:event_lbl_loopMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        goToPrevious();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        goToNextSong();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminPanel().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

        
    public void playSong(int index)
    {
        if(index<songfiles.size())
        {
            MC.Stop();
            File songfile=songfiles.get(index);
            String pathfile=songfile.getAbsolutePath();
            selectedSongIndex=index;
            MC.Play(pathfile);
            
            
             
       }
        else
        {
            System.out.print("No Songs");
        }
    }
    
    public void goToNextSong()
    {
        ++selectedSongIndex;
        playSong(selectedSongIndex);
    }
    
    public void goToPrevious()
    {
        --selectedSongIndex;
        playSong(selectedSongIndex);
    }

    public void startProgram(int index)
    {
        playSong(index);
    }

    
    
    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_play;
    private javax.swing.JLabel counter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JLabel lbl_loop;
    private javax.swing.JLabel lbl_open;
    private javax.swing.JLabel lbl_pause;
    public static javax.swing.JLabel lbl_songnm;
    private javax.swing.JLabel lbl_stop;
    // End of variables declaration//GEN-END:variables
}
