/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoPackage;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class RegisterUser extends javax.swing.JFrame {

    /**
     * Creates new form RegisterUser
     */
    String email,pass,cnf_pass,usernm;

    
    
    public RegisterUser() {
        initComponents();
    }

    public static Connection setConnection()
    {
        Connection con=null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
                 con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abmusicplayerdb", "root", "");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        return con;
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_cnf_password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        btn_register = new javax.swing.JButton();
        btn_reset1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 476));
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(102, 153, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USER REGISTRATION");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 204)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1020, 59);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel3.setText("UserName :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(177, 186, 160, 40);

        txt_email.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_email);
        txt_email.setBounds(396, 102, 450, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel4.setText("Email :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 102, 170, 40);

        txt_username.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_username);
        txt_username.setBounds(396, 186, 450, 40);

        txt_cnf_password.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txt_cnf_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cnf_password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        getContentPane().add(txt_cnf_password);
        txt_cnf_password.setBounds(400, 340, 450, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("Confirm Password :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(170, 340, 160, 40);

        btn_register.setBackground(new java.awt.Color(153, 153, 255));
        btn_register.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_register.setForeground(new java.awt.Color(51, 51, 255));
        btn_register.setText("REGISTER");
        btn_register.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_register);
        btn_register.setBounds(500, 410, 100, 36);

        btn_reset1.setBackground(new java.awt.Color(153, 153, 255));
        btn_reset1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btn_reset1.setForeground(new java.awt.Color(51, 51, 255));
        btn_reset1.setText("RESET");
        btn_reset1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        btn_reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reset1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset1);
        btn_reset1.setBounds(280, 410, 100, 36);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("Password :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(177, 267, 160, 40);

        txt_password.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txt_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_password.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        getContentPane().add(txt_password);
        txt_password.setBounds(396, 267, 450, 40);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/arrow.png"))); // NOI18N
        jButton1.setText("BACK");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 423, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/user registration.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1030, 480);

        setBounds(0, 0, 1040, 515);
    }// </editor-fold>//GEN-END:initComponents

     public  boolean checkUsername(String unm) throws SQLException, ClassNotFoundException
    {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abmusicplayerdb","root","");
        PreparedStatement ps;
        con.setTransactionIsolation(Connection.TRANSACTION_READ_COMMITTED);
        ResultSet rs;
        boolean checkUser=false;
        String qry="SELECT * FROM userlogin where UserName=?";
        ps=con.prepareStatement(qry);
        ps.setString(1, unm);
        rs=ps.executeQuery();
        if(rs.next())
        {
            checkUser=true;
            return checkUser;
        }
        else
        {
            checkUser=false;
            return checkUser;
        }
    }
    
    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        try {
            // TODO add your handling code here:
            
            email=txt_email.getText();
            usernm=txt_username.getText();
            pass=txt_password.getText().toString();
            cnf_pass=txt_cnf_password.getText().toString();
            if(email.equals("")||usernm.equals("")||pass.equals("")||cnf_pass.equals(""))
            {
                JOptionPane.showMessageDialog(null,"Please Fill all the fields!");
            }
            else if(!pass.equals(cnf_pass))
            {
                JOptionPane.showMessageDialog(null,"ReType the Password Again!!!");
            }
            else if(checkUsername(usernm))
            {
                JOptionPane.showMessageDialog(null,"Username already exists");
            }
            else
            {
                PreparedStatement ps;
                String query=" INSERT INTO userlogin (UserName,Password,EmailID,VerifyCode) VALUES(?,?,?,'"+0+"') ";
                ps=setConnection().prepareStatement(query);
                ps.setString(1, usernm);
                ps.setString(2, pass);
                ps.setString(3, email);
                if(ps.executeUpdate()>0)
                {
                    JOptionPane.showMessageDialog(null,"New User Added Succesfully !!!");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegisterUser.class.getName()).log(Level.SEVERE, null, ex);
        }
            

    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reset1ActionPerformed
        // TODO add your handling code here:
        txt_email.setText("");
        txt_password.setText("");
        txt_cnf_password.setText("");
        txt_username.setText("");
    }//GEN-LAST:event_btn_reset1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginUser().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JButton btn_reset1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JLabel lbl_back1;
    private javax.swing.JLabel lbl_back2;
    private javax.swing.JLabel lbl_back3;
    private javax.swing.JLabel lbl_back4;
    private javax.swing.JPasswordField txt_cnf_password;
    private javax.swing.JTextField txt_email;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
