/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoPackage;

import java.sql.Connection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;

/**
 *
 * @author DELL
 */
public class UserLoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form UserLoginWindow
     */
    displayList d2=new displayList();
    public static String songpath;
    MP3_Player_Code mp=new MP3_Player_Code();
    
        public UserLoginWindow() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        user_owned_song_list = new javax.swing.JList<String>();
        jPanel1 = new javax.swing.JPanel();
        player_stater = new javax.swing.JButton();
        add_song = new javax.swing.JButton();
        stopsong = new javax.swing.JButton();
        remove_song = new javax.swing.JButton();
        get_song_metadata = new javax.swing.JButton();
        lbl_back = new javax.swing.JLabel();
        playsong = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Welcome User!");
        setBackground(new java.awt.Color(153, 204, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(88, 8, 8));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("WELCOME USER !!!");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(133, 34, 34)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 5, 780, 44);

        jLabel2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("List Of Songs Owned By User:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(533, 55, 260, 25);

        d2.dispList();
        user_owned_song_list.setModel(d2.songmodel);
        user_owned_song_list.setFont(new java.awt.Font("Times New Roman", 2, 16)); // NOI18N
        songpath=user_owned_song_list.getSelectedValue();
        user_owned_song_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(user_owned_song_list);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(533, 86, 260, 430);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        player_stater.setBackground(new java.awt.Color(153, 137, 211));
        player_stater.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        player_stater.setForeground(new java.awt.Color(0, 0, 153));
        player_stater.setText("START PLAYER");
        player_stater.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        player_stater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                player_staterActionPerformed(evt);
            }
        });

        add_song.setBackground(new java.awt.Color(153, 137, 211));
        add_song.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        add_song.setForeground(new java.awt.Color(0, 0, 153));
        add_song.setText("ADD SONG");
        add_song.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add_song.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_songActionPerformed(evt);
            }
        });

        stopsong.setBackground(new java.awt.Color(153, 137, 211));
        stopsong.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        stopsong.setForeground(new java.awt.Color(0, 0, 153));
        stopsong.setText("STOP SONG");
        stopsong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stopsong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopsongActionPerformed(evt);
            }
        });

        remove_song.setBackground(new java.awt.Color(153, 137, 211));
        remove_song.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        remove_song.setForeground(new java.awt.Color(0, 0, 153));
        remove_song.setText("REMOVE SONG");
        remove_song.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        remove_song.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_songActionPerformed(evt);
            }
        });

        get_song_metadata.setBackground(new java.awt.Color(153, 137, 211));
        get_song_metadata.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        get_song_metadata.setForeground(new java.awt.Color(0, 0, 153));
        get_song_metadata.setText("GET SONG METADATA");
        get_song_metadata.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        get_song_metadata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_song_metadataActionPerformed(evt);
            }
        });

        lbl_back.setBackground(new java.awt.Color(153, 137, 211));
        lbl_back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_back.setForeground(new java.awt.Color(0, 0, 153));
        lbl_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/signout.jpg"))); // NOI18N
        lbl_back.setBorder(new javax.swing.border.MatteBorder(null));
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_backMouseReleased(evt);
            }
        });

        playsong.setBackground(new java.awt.Color(153, 137, 211));
        playsong.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        playsong.setForeground(new java.awt.Color(0, 0, 153));
        playsong.setText("PLAY SONG");
        playsong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        playsong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playsongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(get_song_metadata, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(playsong, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_song, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(remove_song, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(stopsong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(player_stater, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_back, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(player_stater, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playsong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stopsong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_song, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remove_song, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(get_song_metadata, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lbl_back)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(7, 55, 520, 460);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/music-3888684_1280.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 530);

        setBounds(0, 0, 816, 564);
    }// </editor-fold>//GEN-END:initComponents

    
    private void remove_songActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_songActionPerformed
        try {

            // TODO add your handling code here:
            songpath=user_owned_song_list.getSelectedValue();

            String unm=LoginUser.getData();
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abmusicplayerdb","root","");
            String qry2="Select * from "+unm+" ";
            Statement ps=con.createStatement();
            ResultSet rs=ps.executeQuery(qry2);
            int id,no=0;
            String nm;
            while(rs.next())
            {
             id=rs.getInt("SongId");
             nm=rs.getString("SongNames");
             if(nm.equals(songpath))
             {
                 no=id;
             }
             
            } 
                
            
            String qry="Delete  from "+unm+" where SongId=? ";
            PreparedStatement ps1=con.prepareStatement(qry);
            ps1.setInt(1, no);
            int i=0;
            i=ps1.executeUpdate();
            
            if(i>0)
            {
                JOptionPane.showMessageDialog(null, "Song Removed Successfully!!!");
                d2.dispList();
                user_owned_song_list.setModel(d2.songmodel);
                
            }
            else if(i==0)
            {
                JOptionPane.showMessageDialog(null, "Song Removal Failed!!!");

            }        } 
        catch (ClassNotFoundException ex) {
            Logger.getLogger(UserLoginWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UserLoginWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        
    }//GEN-LAST:event_remove_songActionPerformed

    private void get_song_metadataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_song_metadataActionPerformed
        // TODO add your handling code here:
        this.dispose();
        User_GetSongMetaData ug=new User_GetSongMetaData();
        ug.setVisible(true);
        songpath=user_owned_song_list.getSelectedValue();
        ug.mp.getMetadataOfSong(songpath);
    }//GEN-LAST:event_get_song_metadataActionPerformed

    private void player_staterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_player_staterActionPerformed
        // TODO add your handling code here:
        this.dispose();
        User_MP3Player_GUI gui=new User_MP3Player_GUI();
        gui.setVisible(true);
        
    }//GEN-LAST:event_player_staterActionPerformed

    private void stopsongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopsongActionPerformed
        // TODO add your handling code here:
        mp.Stop();
        
        
    }//GEN-LAST:event_stopsongActionPerformed

    private void add_songActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_songActionPerformed
        // TODO add your handling code here:
        this.dispose();
        User_ADDSong s1=new User_ADDSong();
        s1.setVisible(true);
        
    }//GEN-LAST:event_add_songActionPerformed

    private void playsongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playsongActionPerformed
        // TODO add your handling code here:
        songpath=user_owned_song_list.getSelectedValue();
        mp.Stop();
        mp.Play(songpath);
    }//GEN-LAST:event_playsongActionPerformed

    private void lbl_backMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseReleased
        // TODO add your handling code here:
        int input=JOptionPane.showConfirmDialog(null, "Do you really wanna Exit ???", "LOG-OUT", JOptionPane.YES_NO_CANCEL_OPTION);
        if(input==0)
        {
        this.dispose();
        new LoginUser().setVisible(true);
        }
        else
        {
            
        }
    }//GEN-LAST:event_lbl_backMouseReleased

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_song;
    private javax.swing.JButton get_song_metadata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JButton player_stater;
    private javax.swing.JButton playsong;
    private javax.swing.JButton remove_song;
    private javax.swing.JButton stopsong;
    public javax.swing.JList<String> user_owned_song_list;
    // End of variables declaration//GEN-END:variables
}
