/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoPackage;

/**
 *
 * @author DELL
 */
public class User_GetSongMetaData extends javax.swing.JFrame {

    /**
     * Creates new form User_GetSongMetaData
     */
    Mp3Parse mp=new Mp3Parse();
    
    public User_GetSongMetaData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        metadata_list = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        lbl_content = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SONG METADATA");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 9, 536, 70);

        metadata_list.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        metadata_list.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        metadata_list.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(metadata_list);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 164, 536, 301);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        jLabel4.setText("Contents Of the Song:");
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 90, 221, 24);

        lbl_content.setFont(new java.awt.Font("Tempus Sans ITC", 1, 16)); // NOI18N
        lbl_content.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_content);
        lbl_content.setBounds(257, 90, 289, 24);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("METADATA OF SONG:");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 120, 536, 38);

        lbl_back.setBackground(new java.awt.Color(153, 137, 211));
        lbl_back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_back.setForeground(new java.awt.Color(0, 0, 153));
        lbl_back.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/arrow.png"))); // NOI18N
        lbl_back.setText(" BACK");
        lbl_back.setBorder(new javax.swing.border.MatteBorder(null));
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_backMouseReleased(evt);
            }
        });
        getContentPane().add(lbl_back);
        lbl_back.setBounds(10, 470, 120, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/music-3888684_1280.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 550, 510);

        setBounds(0, 0, 572, 553);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_backMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseReleased
        // TODO add your handling code here:
        this.hide();
        new UserLoginWindow().setVisible(true);
    }//GEN-LAST:event_lbl_backMouseReleased

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_back;
    public static javax.swing.JLabel lbl_content;
    public static javax.swing.JList<String> metadata_list;
    // End of variables declaration//GEN-END:variables
}
