/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoPackage;

import java.sql.*;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Verify_Users extends javax.swing.JFrame {

    /**
     * Creates new form Verify_Users
     */
    
    private String username;
    private String verify[];
    
    public Verify_Users() {
        initComponents();
    }

    
    
    private void connectDatabase()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abmusicplayerdb", "root","");
            Statement stmt=con.createStatement();
            String qry="SELECT count('UserName') FROM userlogin where VerifyCode='0'";
            ResultSet rs=stmt.executeQuery(qry);
            rs.next();
            int i=rs.getInt(1);
            verify=new String[i];
            i=0;
            String qry2="SELECT UserName FROM userlogin where VerifyCode='0'";
            rs=stmt.executeQuery(qry2);
            while(rs.next())
            {
                verify[i++]=rs.getString("UserName");
            }
            
            
        } 
        catch (ClassNotFoundException ex) 
        {
            Logger.getLogger(Verify_Users.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) {
            Logger.getLogger(Verify_Users.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    private  void verifyUsers()
    {
        connectDatabase();
        if(verify.length>0)
        {
            for(int j=0;j<verify.length;j++)
            {
                   combobox_usernms.addItem(verify[j]);
                   
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "All Users are Verified!!!");
            combobox_usernms.removeAllItems();
            this.dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        combobox_usernms = new javax.swing.JComboBox<String>();
        delete_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_back = new javax.swing.JLabel();
        verify_btn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEARCH");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 153)));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 200, 201, 34);

        verifyUsers();
        combobox_usernms.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combobox_usernms.setForeground(new java.awt.Color(0, 51, 51));
        combobox_usernms.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));
        getContentPane().add(combobox_usernms);
        combobox_usernms.setBounds(390, 200, 290, 34);

        delete_btn.setBackground(new java.awt.Color(204, 204, 204));
        delete_btn.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        delete_btn.setForeground(new java.awt.Color(102, 0, 0));
        delete_btn.setText("DELETE");
        delete_btn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        getContentPane().add(delete_btn);
        delete_btn.setBounds(390, 290, 186, 54);

        jLabel2.setBackground(new java.awt.Color(102, 102, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VERIFY USERS");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(38, 14, 711, 130);

        lbl_back.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbl_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/arrow.png"))); // NOI18N
        lbl_back.setText("BACK");
        lbl_back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 153, 255), 2));
        lbl_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_backMouseReleased(evt);
            }
        });
        getContentPane().add(lbl_back);
        lbl_back.setBounds(10, 360, 50, 40);

        verify_btn1.setBackground(new java.awt.Color(204, 204, 204));
        verify_btn1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        verify_btn1.setForeground(new java.awt.Color(102, 0, 0));
        verify_btn1.setText("VERIFY");
        verify_btn1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 102)));
        verify_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(verify_btn1);
        verify_btn1.setBounds(160, 290, 186, 54);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DemoPackage/verify.jpeg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 800, 410);

        setBounds(0, 0, 816, 451);
    }// </editor-fold>//GEN-END:initComponents

    private void verify_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify_btn1ActionPerformed
        try {
            // TODO add your handling code here:
            System.out.print("hii");
            int res;
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abmusicplayerdb", "root","");
            Statement stmt=con.createStatement();
            String selected=combobox_usernms.getSelectedItem().toString();
            String query="UPDATE userlogin SET VerifyCode=1 where UserName='"+selected+" ' ";
            String qr3="CREATE TABLE "+selected+" ("
                        + "SongNames VARCHAR (20000),"
                        + "SongId INT(100) NOT NULL AUTO_INCREMENT  UNIQUE)";
            stmt.executeUpdate(qr3);
            res=stmt.executeUpdate(query);
            if(res!=0)
            {
                JOptionPane.showMessageDialog(null, selected+" verified Successfully...");
                verifyUsers();
            }
            else
            {
                JOptionPane.showMessageDialog(null, selected+" verificaton Failed...");
            }
        }
        catch (ClassNotFoundException ex) 
        {
            Logger.getLogger(Verify_Users.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Verify_Users.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_verify_btn1ActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        try{
        int res;
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/abmusicplayerdb", "root","");
            Statement stmt=con.createStatement();
            String selected=combobox_usernms.getSelectedItem().toString();
            String query="DELETE FROM  userlogin where  UserName='"+selected+" ' ";
            res=stmt.executeUpdate(query);
            if(res!=0)
            {
                JOptionPane.showMessageDialog(null, selected+" deleted Successfully...");
                verifyUsers();
            }
            else
            {
                JOptionPane.showMessageDialog(null, selected+" verificaton Failed...");
            }
        }
        catch (ClassNotFoundException ex) 
        {
            Logger.getLogger(Verify_Users.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(Verify_Users.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void lbl_backMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_backMouseReleased
        // TODO add your handling code here:
        this.dispose();
        new AdminPanel().setVisible(true);
        
    }//GEN-LAST:event_lbl_backMouseReleased

    
    /**
     * @param args the command line arguments
     */
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox_usernms;
    private javax.swing.JButton delete_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_back;
    private javax.swing.JButton verify_btn1;
    // End of variables declaration//GEN-END:variables
}
